Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,13 +33,14 @@ jobs:
           cd /home/dev/web/portfolio
 
           # Run the installer
-          bash ./install.sh || exit_code=$?
-          exit_code=${exit_code:-0}
+          bash ./install.sh
 
-          if [ "$exit_code" -eq 100 ]; then
-              echo "First-time setup done, skipping failure."
-              exit 100
-          else
-              exit $exit_code
+          exit_code=\$? 
+          exit_code=\${exit_code:-0}; 
+          if [ \$exit_code -eq 100 ]; 
+            then echo 'First-time setup done, skipping failure'; 
+            exit 0; 
+          else 
+            exit \$exit_code; 
           fi
         EOF
